export type Payment = {
  id: string;
  amount: number;
  status: "pending" | "processing" | "success" | "failed";
  email: string;
  food: string;
  date: string;
  address: string;
};

export const paymentsData: Payment[] = [
  {
    id: "m5gr84i9",
    amount: 316,
    status: "success",
    email: "ken99@example.com",
    food: "2 foods",
    date: "2024/12/20",
    address: "2024/12/СБД, 12-р хороо, СБД нэгдсэн эмнэлэг",
  },
  {
    id: "3u1reuv4",
    amount: 242,
    status: "success",
    email: "Abe45@example.com",
    food: "2 foods",
    date: "2024/12/20",
    address: "2024/12/СБД, 12-р хороо, СБД нэгдсэн эмнэлэг",
  },
  {
    id: "derv1ws0",
    amount: 837,
    status: "processing",
    email: "Monserrat44@example.com",
    food: "2 foods",
    date: "2024/12/20",
    address: "2024/12/СБД, 12-р хороо, СБД нэгдсэн эмнэлэг",
  },
  {
    id: "5kma53ae",
    amount: 874,
    status: "success",
    email: "Silas22@example.com",
    food: "2 foods",
    date: "2024/12/20",
    address: "2024/12/СБД, 12-р хороо, СБД нэгдсэн эмнэлэг",
  },
  {
    id: "bhqecj4p",
    amount: 721,
    status: "failed",
    email: "carmella@example.com",
    food: "2 foods",
    date: "2024/12/20",
    address: "2024/12/СБД, 12-р хороо, СБД нэгдсэн эмнэлэг",
  },
  {
    id: "x7k2mn3p",
    amount: 450,
    status: "pending",
    email: "sarah.jones@email.com",
    food: "3 foods",
    date: "2024/12/21",
    address: "Сүхбаатар дүүрэг, 1-р хороо, Central Tower",
  },
  {
    id: "w9f5t8q1",
    amount: 189,
    status: "success",
    email: "mike.wilson@gmail.com",
    food: "1 food",
    date: "2024/12/21",
    address: "Чингэлтэй дүүрэг, 5-р хороо, Sky Residence",
  },
  {
    id: "v3b7n2k4",
    amount: 625,
    status: "processing",
    email: "elena.rodriguez@yahoo.com",
    food: "4 foods",
    date: "2024/12/22",
    address: "Баянзүрх дүүрэг, 20-р хороо, Blue Sky Tower",
  },
  {
    id: "u6c9m1l8",
    amount: 298,
    status: "failed",
    email: "david.kim@hotmail.com",
    food: "2 foods",
    date: "2024/12/22",
    address: "Хан-Уул дүүрэг, 15-р хороо, Grand Plaza",
  },
  {
    id: "t4d8r5n7",
    amount: 512,
    status: "success",
    email: "anna.petrov@email.com",
    food: "3 foods",
    date: "2024/12/23",
    address: "Сонгинохайрхан дүүрэг, 7-р хороо, Misheel Expo",
  },
  {
    id: "s2e6w9m3",
    amount: 367,
    status: "pending",
    email: "james.brown@gmail.com",
    food: "2 foods",
    date: "2024/12/23",
    address: "Баянгол дүүрэг, 3-р хороо, Corporate Hotel",
  },
  {
    id: "r1f4q7k5",
    amount: 789,
    status: "processing",
    email: "lisa.chen@yahoo.com",
    food: "5 foods",
    date: "2024/12/24",
    address: "Сүхбаатар дүүрэг, 8-р хороо, Premium Office",
  },
  {
    id: "q8g3z2n6",
    amount: 156,
    status: "success",
    email: "robert.taylor@email.com",
    food: "1 food",
    date: "2024/12/24",
    address: "Чингэлтэй дүүрэг, 12-р хороо, Modern Complex",
  },
  {
    id: "p7h5v1m9",
    amount: 434,
    status: "failed",
    email: "maria.garcia@hotmail.com",
    food: "3 foods",
    date: "2024/12/25",
    address: "Баянзүрх дүүрэг, 25-р хороо, Business Center",
  },
  {
    id: "o4j8x3k2",
    amount: 678,
    status: "success",
    email: "tom.anderson@gmail.com",
    food: "4 foods",
    date: "2024/12/25",
    address: "Хан-Уул дүүрэг, 18-р хороо, Elite Residence",
  },
  {
    id: "n6k2y7l4",
    amount: 223,
    status: "pending",
    email: "sophie.martin@yahoo.com",
    food: "2 foods",
    date: "2024/12/26",
    address: "Сонгинохайрхан дүүрэг, 11-р хороо, Tech Hub",
  },
  {
    id: "m3l9z5q8",
    amount: 545,
    status: "processing",
    email: "alex.johnson@email.com",
    food: "3 foods",
    date: "2024/12/26",
    address: "Баянгол дүүрэг, 6-р хороо, Innovation Center",
  },
  {
    id: "l2n4b8r1",
    amount: 398,
    status: "success",
    email: "emma.davis@gmail.com",
    food: "2 foods",
    date: "2024/12/27",
    address: "Сүхбаатар дүүрэг, 14-р хороо, Trade Center",
  },
  {
    id: "k9o7c3t6",
    amount: 712,
    status: "failed",
    email: "kevin.lee@hotmail.com",
    food: "4 foods",
    date: "2024/12/27",
    address: "Чингэлтэй дүүрэг, 9-р хороо, Executive Tower",
  },
  {
    id: "a8y4t3u7",
    amount: 512,
    status: "failed",
    email: "joshua.king@email.com",
    food: "3 foods",
    date: "2025/01/01",
    address: "Баянгол дүүрэг, 19-р хороо, Holiday Resort",
  },
  {
    id: "z1z7v2w5",
    amount: 398,
    status: "success",
    email: "stephanie.scott@gmail.com",
    food: "3 foods",
    date: "2025/01/02",
    address: "Сүхбаатар дүүрэг, 23-р хороо, Business Hub",
  },
];
